# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    working_directory: ~/pantheon
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --ignore-optional --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  unittest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Run unit tests
          command: ls -al node_modules/.bin/ && yarn test:unit
  integrationtest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run integration tests
          command: yarn test:e2e:ci
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint files
          command: yarn format
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
  typecheck:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Typecheck
          command: ls -al && node_modules/.bin/ && yarn tsc
  storybook:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build storybook
          command: yarn storybook

workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - install
      - build:
          requires:
            - install
            - lint
      - storybook:
          requires:
            - install
            - lint
      - unittest:
          requires:
            - install
            - build
      - integrationtest:
          requires:
            - install
            - build
